### ISSUE TITLE
Error when executing queries

### ISSUE THREAD

**Issue by cgivre** [JohnOmernik/jupyter_drill#1]
I seem to be getting an error when I try to execute a query.  The error seems to be inconsistent in that some plugins cause this error and others do not.  I did validate the query and it is correct.

Here is the stack trace:

```python
0 Records in Approx 0 seconds

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-22bc49393c40> in <module>
----> 1 get_ipython().run_cell_magic('drill', '', 'SELECT useragent\nFROM splunk.main\nLIMIT 50\n')

~/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2379             with self.builtin_trap:
   2380                 args = (magic_arg_s, cell)
-> 2381                 result = fn(*args, **kwargs)
   2382             return result
   2383 

<decorator-gen-126> in drill(self, line, cell)

~/anaconda3/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/anaconda3/lib/python3.7/site-packages/drill_core/drill_base.py in drill(self, line, cell)
    369                     print("I am sorry, I don't know what you want to do with your line magic, try just %" + self.name_str + "for help options")
    370         else: # This is run is the cell is not none, thus it's a cell to process  - For us, that means a query
--> 371             self.handleCell(cell)
    372 

~/anaconda3/lib/python3.7/site-packages/integration_core/integration_base.py in handleCell(self, cell)
    172                         else:
    173                             # Hack to hide the index field
--> 174                             display(qgrid.show_grid(result_df, grid_options={'forceFitColumns': False, 'defaultColumnWidth': int(self.opts['qg_defaultColumnWidth'][0])}, column_definitions={ 'index': { 'maxWidth': 0, 'minWidth': 0, 'width': 0  } }))
    175 
    176                     else:

~/anaconda3/lib/python3.7/site-packages/qgrid/grid.py in show_grid(data_frame, show_toolbar, precision, grid_options, column_options, column_definitions, row_edit_callback)
    498     elif not isinstance(data_frame, pd.DataFrame):
    499         raise TypeError(
--> 500             "data_frame must be DataFrame or Series, not %s" % type(data_frame)
    501         )
    502 

TypeError: data_frame must be DataFrame or Series, not <class 'NoneType'>

```

Here is the code:

```python
from drill_core import Drill
ipy = get_ipython()
Drill = Drill(ipy, drill_embedded=True,  pd_display_grid="qgrid")
ipy.register_magics(Drill)

# New Cell
%drill connect

#New Cell
%%drill
SELECT * FROM .... 
```

**Comment by JohnOmernik** [comment]
A few things:

Can you:
Ensure jupyter_drill AND jupyter_integration_base are both up-todate?  git pull both, and python setup.py install both of them. Please start with the integration base. 

Try it then.

Also, post here what you are using for qgrid and pandas versions.  

Are you using Jupyter Notebook or Jupyter Lab? 

You may want to share what extension versions you are using as well.

**Comment by JohnOmernik** [comment]
Ok, also, just git pull jupyter_integration_base. 

I added a check so it doesn't try to display a "no results" df (None type).  Not sure why I haven't gotten that before. But ya. Give it a try.

**Comment by cgivre** [comment]
Hey @JohnOmernik 
The mods you made fixed the issue in that it is now not returning error messages.  Here's the weird thing though, I'm working on a Splunk plugin for Drill (https://github.com/apache/drill/pull/2089) and when I execute queries for that in the notebook, I get zero results.  However, if I execute the same query in Drill directly, (or in Superset), I get results.

Any suggestions or ideas on how to debug?

**Comment by cgivre** [comment]
![Screen Shot 2020-08-28 at 9 54 12 AM](https://user-images.githubusercontent.com/5513150/91571889-76cd3880-e914-11ea-98b4-118b7da249c2.png)

**Comment by JohnOmernik** [comment]
I am working on that now myself. Can you share a basic query that you are trying?

**Comment by cgivre** [comment]
![Screen Shot 2020-08-28 at 9 54 45 AM](https://user-images.githubusercontent.com/5513150/91572117-85b3eb00-e914-11ea-8adf-ca137a384908.png)

**Comment by cgivre** [comment]
Basically any query using the Splunk plugin doesn't return results.   I was using:

```sql
SELECT useragent, parse_user_agent(useragent, 'DeviceClass') as device_class, 
parse_user_agent(useragent, 'BrowserFamily') as browserFamily
FROM splunk.main 
LIMIT 50
```

But the query below also fails. 
```sql 
SELECT * 
FROM splunk.main 
LIMIT 10
```

**Comment by JohnOmernik** [comment]
This is very strange.  

Can you test the type of prev_drill (print type(prev_drill))

**Comment by cgivre** [comment]
@JohnOmernik 
I upgraded, and did some mucking around with the query.  I'm not sure why or what I did differently but it is now working.  Thanks and I'll close the issue.
